version: '3'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SMTP_HOST=${SMTP_HOST- }
      - SMTP_USER=${SMTP_USER- }
      - SMTP_PASS=${SMTP_PASS- }
      - SMTP_EMAIL=${SMTP_EMAIL- }
    volumes:
      - "./data:${DATA_DIR}"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  devserver:
    image: localstack-ruby
    ports:
      - "25:25"
      - "1080:1080"
    tty: true
    command: bash -c "mailcatcher --smtp-port 25 --smtp-ip 0.0.0.0 --http-ip 0.0.0.0 && /bin/bash"
